# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kDHBb3hd3l0PH6KVJV5OQvAQ7vj7pFp
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive
!git clone https://github.com/ultralytics/ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ultralytics
!pip install -e .

!yolo train data=/content/drive/MyDrive/virus.v3i.yolov8/data.yaml model=yolov8n.yaml epochs=300 imgsz=640 batch=16 lr0=0.001 weight_decay=0.0005

from ultralytics import YOLO

# Initialize a YOLO model for training without pre-trained weights
model = YOLO('yolov8n.yaml')

# Start training
results = model.train(data='/content/drive/MyDrive/virus.v3i.yolov8/data.yaml', epochs=300, imgsz=640,pretrained=False,amp=False)



from ultralytics import YOLO

# 加载训练好的模型
model = YOLO('/content/drive/MyDrive/ultralytics/runs/detect/train3/weights/best.pt')

# 在测试集上进行验证
results = model.val(data='/content/drive/MyDrive/virus.v3i.yolov8/data.yaml', imgsz=640, split='test',conf=0.5)

# 打印测试集结果
print(results)

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ultralytics
!pip install -e .


!yolo task=detect mode=train model=/content/drive/MyDrive/ultralytics/ultralytics/yolov8CA.yaml data=/content/drive/MyDrive/virus.v3i.yolov8/data.yaml epochs=300 imgsz=640  pretrained=False amp=False

!yolo task=detect mode=train model=yolov8n.pt data=/content/virus-4/data.yaml epochs=300 imgsz=640 batch=16

!yolo val model=/content/drive/MyDrive/ultralytics/runs/detect/train7/weights/best.pt data=/content/drive/MyDrive/virus.v3i.yolov8/data.yaml imgsz=640 split=test conf=0.5

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="s28yYk3gv0a3UZL3HoFx")
project = rf.workspace("virus-ebbve").project("virus-7fn0n")
version = project.version(1)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ultralytics
!pip install -e .

!yolo task=detect mode=train model=yolov8n.yaml data=/content/virus-4/data.yaml epochs=300 imgsz=640  lr0=0.001 weight_decay=0.0005

!yolo val model=/content/drive/MyDrive/ultralytics/runs/detect/train6/weights/best.pt data=/content/virus-4/data.yaml imgsz=640 split=test conf=0.5

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="s28yYk3gv0a3UZL3HoFx")
project = rf.workspace("virus-ebbve").project("virus-7fn0n")
version = project.version(4)
dataset = version.download("yolov8")
!pip install roboflow

# %cd /content/drive/MyDrive/ultralytics
# !pip install -e .
import os
os.environ["WANDB_MODE"] = "disabled"

from ultralytics import YOLO

# 加载模型
model = YOLO('yolov8n.pt')

# 开始训练
model.train(data='/content/virus-4/data.yaml', epochs=300, imgsz=640, lr0=0.001, weight_decay=0.0005)



!yolo task=detect mode=val model=/content/drive/MyDrive/ultralytics/runs/detect/train11/weights/best.pt data=/content/virus-4/data.yaml split=test

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="s28yYk3gv0a3UZL3HoFx")
project = rf.workspace("virus-ebbve").project("virus-7fn0n")
version = project.version(3)
dataset = version.download("yolov8")

from ultralytics import YOLO

# 加载模型
model = YOLO('yolov8n.pt')

# 开始训练
model.train(data='/content/drive/MyDrive/ultralytics/virus-3/data.yaml', epochs=300, imgsz=640, lr0=0.001, weight_decay=0.0005)

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="s28yYk3gv0a3UZL3HoFx")
project = rf.workspace("virus-ebbve").project("virus-7fn0n")
version = project.version(4)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8n.pt data=//content/drive/MyDrive/ultralytics/virus-5/data.yaml epochs=300 imgsz=640 batch=16 lr0=0.001 weight_decay=0.0005

# %cd  /content/drive/MyDrive/ultralytics
# !pip install -e .
import os
os.environ['WANDB_MODE'] = 'disabled'

!yolo task=detect mode=train model=/content/drive/MyDrive/ultralytics/ultralytics/yolov8CA.yaml data=/content/drive/MyDrive/ultralytics/virus-4/data.yaml epochs=300 imgsz=640 batch=8

from ultralytics import YOLO

# Load a COCO-pretrained YOLO11n model
model = YOLO("yolo11n.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/drive/MyDrive/ultralytics/virus-4/data.yaml", epochs=300, imgsz=640)

!yolo task=detect mode=val model=/content/drive/MyDrive/ultralytics/runs/detect/train12/weights/best.pt data=/content/drive/MyDrive/ultralytics/virus-3/data.yaml split=test

# !pip install ultralytics
from ultralytics import YOLO
import os
os.environ['WANDB_MODE'] = 'disabled'
# Load a COCO-pretrained YOLO11n model
model = YOLO("yolov8m.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", epochs=300, imgsz=640)

from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'
# Load a COCO-pretrained YOLO11n model
model = YOLO("yolov8n.yaml")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", epochs=300, imgsz=640,pretrained=False)



from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train4/weights/best.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.val(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", split='test',imgsz=640)

from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'
# Load a COCO-pretrained YOLO11n model
model = YOLO("yolov8n.yaml")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/drive/MyDrive/ultralytics/virus-4/data.yaml", epochs=300, imgsz=640,pretrained=False)

from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.val(data="/content/drive/MyDrive/ultralytics/virus-4/data.yaml", split='test',imgsz=640)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ultralytics
# !pip install -e .
from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/ultralytics/yolov8CA.yaml")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", epochs=300, imgsz=640,pretrained=False)

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.val(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", split='test',imgsz=640)

from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train2/weights/best.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.val(data="/content/drive/MyDrive/ultralytics/virus-5/data.yaml", split='test',imgsz=640)

from ultralytics import YOLO
# 加载训练好的模型
model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/85imagesCBAM/weights/best.pt")
# 将模型转为onnx格式
success = model.export(format='onnx')

from google.colab import drive
drive.mount('/content/drive')

import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

from roboflow import Roboflow
rf = Roboflow(api_key="s28yYk3gv0a3UZL3HoFx")
project = rf.workspace("virus-ebbve").project("upscalevirus")
version = project.version(2)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ultralytics
# pip install -e .
from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/ultralytics/yolov8CA.yaml").load('yolov8n.pt')

results = model.train(data="/content/drive/MyDrive/upscalevirus2-3/data.yaml", epochs=300, imgsz=640)

from ultralytics import YOLO


import os
os.environ['WANDB_MODE'] = 'disabled'

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.val(data="/content/upscalevirus-2/data.yaml", split='test',imgsz=640)